name: "JCR Docker Build"

on:
  workflow_dispatch:



jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get semantic version from file
        id: getSemver
        run: echo "::set-output name=semver::$(cat VERSION | tr -d ' \t\n\r' )"


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: artifact.techblog.co.il
          username: ${{ secrets.JCR_USERNAME }}
          password: ${{ secrets.JCR_TOKEN }}


      - name: Build Images
        uses: docker/build-push-action@v4
        with:
          registry: artifact.techblog.co.il
          cache-from: type=registry,ref=user/app:latest
          context: .
#           platforms: linux/amd64
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker/wassist:latest
            docker/wassist:${{ steps.getSemver.outputs.semver }}     


#       - name: Push images to artifactory
#         run: |
#           docker login artifact.techblog.co.il -u ${{ secrets.JCR_USERNAME }} -p ${{ secrets.JCR_TOKEN }}
#           docker tag wassist artifact.techblog.co.il/docker/wassist:latest
#           docker tag wassist artifact.techblog.co.il/docker/wassist:${{ steps.getSemver.outputs.semver }}
#           docker push artifact.techblog.co.il/docker/wassist:latest
#           docker push artifact.techblog.co.il/docker/wassist:${{ steps.getSemver.outputs.semver }}
        
